# Generated by Django 3.1 on 2020-10-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_register_time_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
